---
- name: Set mariadb repository
  copy: src=mariadb.repo dest=/etc/yum.repos.d/mariadb.repo mode=0644 owner=root group=root force=yes
  notify: yum update

- name: install mariadb
  yum: name={{ item }} state=present 
  notify: restart mariadb
  with_items:
    - MariaDB
    - MariaDB-devel
    - MariaDB-client
    - MariaDB-server
    - MySQL-python

- yum: name=MySQL-python state=absent

